//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PictureFile()
        {
            this.PicturePersons = new HashSet<PicturePerson>();
            this.PictureFileGroupLookups = new HashSet<PictureFileGroupLookup>();
        }
    
        public int Id { get; set; }
        public string FilePath { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public bool IsConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicturePerson> PicturePersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureFileGroupLookup> PictureFileGroupLookups { get; set; }
    }
}
